import React from 'react'
import GameContainer from './GameContainer'
import Instructions from './Instructions'
import StartButton from '../components/StartButton'
import TurnButton from '../components/TurnButton'
import Choice from '../components/Choice'
import UserInfo from '../components/UserInfo'